//! OpenAPI 3.1 schema, served at `/openapi.json`. We deliberately
//! list paths and components by hand here rather than via the
//! `#[derive(OpenApi)]` `paths(...)` attribute so adding a new
//! handler is a one-liner change.

use crate::cluster::GpuSample;
use crate::db;
use crate::handlers::{activity, builder, catalog, cluster, deploy, fs, me, runs};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "rustorch console API",
        description = "HTTP/JSON-RPC backend for the rustorch console UI (doc v0.7.2 §Reference/Console API).",
        version = "0.0.1",
    ),
    paths(
        me::me,
        me::workspace,
        cluster::gpus,
        cluster::health,
        catalog::list_models,
        catalog::list_datasets,
        catalog::get_dataset,
        runs::list,
        runs::get_one,
        runs::create,
        runs::start,
        runs::pause,
        runs::resume,
        runs::stop,
        runs::fork,
        runs::curves,
        runs::hparams,
        runs::code,
        runs::log,
        runs::checkpoints,
        runs::save_checkpoint,
        runs::artifacts,
        runs::system,
        fs::tree,
        fs::read_file,
        fs::write_file,
        fs::problems,
        fs::run_cargo,
        builder::get_current,
        builder::put_current,
        builder::presets,
        deploy::deploy,
        deploy::register_dataset,
        activity::list,
    ),
    components(schemas(
        me::MeResponse,
        me::WorkspaceResponse,
        GpuSample,
        cluster::ClusterHealth,
        catalog::ModelEntry,
        catalog::DatasetSummary,
        catalog::DatasetDetail,
        runs::ListResponse,
        runs::CreateBody,
        runs::ForkBody,
        runs::NewCheckpointBody,
        runs::CurvesResponse,
        runs::HparamsResponse,
        runs::CodeResponse,
        runs::LogLine,
        runs::LogResponse,
        runs::ArtifactEntry,
        runs::SystemSample,
        runs::SystemResponse,
        db::Run,
        db::RunSummary,
        db::RunStatus,
        db::MetricPoint,
        db::Checkpoint,
        db::ActivityEvent,
        fs::TreeEntry,
        fs::FileResponse,
        fs::WriteBody,
        fs::Problem,
        fs::RunBody,
        fs::RunSpawnResponse,
        builder::GraphDoc,
        builder::PresetEntry,
        deploy::DeployBody,
        deploy::DeployResponse,
        deploy::RegisterDatasetBody,
        deploy::RegisterDatasetResponse,
    )),
    tags(
        (name = "me",       description = "Identity & workspace metadata"),
        (name = "cluster",  description = "Cluster topology + GPU samples"),
        (name = "catalog",  description = "Model & dataset registry"),
        (name = "runs",     description = "Run lifecycle + read-only views"),
    )
)]
pub struct ApiDoc;
